### ISSUE TITLE
Bug report: osxfuse-beta package parse error?

### ISSUE THREAD

**Issue by ThomasWaldmann** [caskroom/homebrew-versions#2878] opened 2016-11-13 00:44 UTC
this doesn't work any more. can anybody figure out why?

```
==> brew cask install Caskroom/versions/osxfuse-beta
Error: Cask 'osxfuse-beta' definition is invalid: Bad header line: parse failed
```

I am not used to OS X stuff, I just want to make the travis-ci OSX testing work again for borgbackup:
https://travis-ci.org/borgbackup/borg/jobs/175152465

What i also noted is that it (3.5.3) is not beta any more.

**Comment by ThomasWaldmann** [comment] 2016-11-13 01:03
It would be nice if that could be fixed quickly, currently our CI for OS X is totally broken due to that.

**Comment by vitorgalvao** [comment] 2016-11-13 11:46
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.

> (…)

> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.

**Comment by vitorgalvao** [comment] 2016-11-13 11:46
Also include the output of `brew cask cat osxfuse-beta`. This looks like you have a very old setup.

**Closed by vitorgalvao** 2016-11-13 11:46 UTC

**Comment by ThomasWaldmann** [comment] 2016-11-13 14:15
It's not my setup, it is travis-ci.org. You cannot interactively enter commands there.

**Comment by vitorgalvao** [comment] 2016-11-13 14:28
> It's not my setup, it is travis-ci.org.

Same thing. The setup made to work in Travis, then.

> Error: No available formula with the name "brew-cask" 

Lines like this reinforce that that setup is outdated. `brew-cask` hasn’t been installed separately for months.

Also, not sure why it’s using `osxfuse-beta` instead of `osxfuse`, but as you noted, those are now the same version, so I’ll remove the former from the repo. Try with `osxfuse` instead. `osxfuse-beta` will be removed now.

**Comment by ThomasWaldmann** [comment] 2016-11-13 14:55
I already tried "osxfuse", it says "not found" then.

**Comment by ThomasWaldmann** [comment] 2016-11-13 14:57
We're running that setup since many months btw and it broke 1-2 days ago. So either there is something broken in that package or travis-ci.org has broken/changed their setup somehow.

**Comment by vitorgalvao** [comment] 2016-11-13 15:44
Since the cask hasn’t been touched in 19 days, clearly exists, works fine and passes `audit`, and you have errors in the outputs of your commands that shouldn’t be there, everything indicates the issue is on your side, caused by Travis or not.

Also, since you cannot even give the me the commands I asked you before (from the bug reporting template and the `cat` one), there’s no way to even diagnose this accurately. Until you can do so, there’s nothing we can do.

That `definition is invalid: Bad header line: parse failed` is indicative of an old cask being used with a more recent HBC core.

**Comment by ThomasWaldmann** [comment] 2016-11-13 21:56
OK, thanks for this hint. I have opened a ticket at travis-ci also, maybe they changed their setup somehow causing this.
